spring:
  profiles:
    include: oauth2

  application:
    name: crux-server

  graphql:
    graphiql:
      enabled: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cliary
    username: root
    password: 1234

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration/local
    baseline-version: 0
    fail-on-missing-locations: true

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: false  # hibernate와 flyway 초기화 실행 순서 지정. false로 설정하면 flyway가 먼저 실행됨.

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

  security:
    user:
      name: user
      password: 1234

jwt:
  secret: Hello_This_Is_My_Secret_Key_For_JWT_Hello_This_Is_My_Secret_Key_For_JWT_Hello_This_Is_My_Secret_Key_For_JWT
  access-token-time: 600000  # 10분
  refresh-token-time: 8640000000  # 100일

server:
  port: 8080

  error:
    include-exception: false      # Response ? Exception ? ????
    include-message: always       # Response ? Exception Message ? ???? (never | always | on_param)
    include-stacktrace: never     # Response ? Stack Trace ? ???? (never | always | on_param)
    whitelabel.enabled: true      # ?? ?? ? Spring ?? ?? ??? ?? ??